-- PARTE AEROPORTOS

-- Criando a SEQUENCIA para o ID dos AEROPORTOS
CREATE SEQUENCE SEQ_AEROPORTOS START WITH 1 INCREMENT BY 1;

-- Criando a tabela de AEROPORTOS
CREATE TABLE AEROPORTOS (
    ID_AEROPORTO integer PRIMARY KEY NOT NULL,
    NOME varchar2(3) NOT NULL,
    CIDADE varchar2(20) NOT NULL,
    PAIS varchar2(20) NOT NULL
);

-- select