-- PARTE AERONAVES

-- Criando a SEQUENCIA para o ID das AERONAVES
CREATE SEQUENCE SEQ_AERONAVES START WITH 1 INCREMENT BY 1;

-- Criando a tabela de AERONAVES
CREATE TABLE AERONAVES (
    ID_AERONAVE integer PRIMARY KEY NOT NULL,
    FABRICANTE varchar2(20) NOT NULL,
    MODELO varchar2(10) NOT NULL,
    ANOFAB integer NOT NULL,
    MAPA_ASSENTO integer NOT NULL
);

-- ADICIONANDO A PK PARA MAPA_ASSENTO
ALTER TABLE AERONAVES ADD CONSTRAINT FK_MAPA_ASSENTO FOREIGN KEY (MAPA_ASSENTO) REFERENCES MAPA_ASSENTO(ID_MAPA)
-- select