-- CRIANDO A SEQUENCIA DE CIDADES
CREATE SEQUENCE SEQ_CIDADES START WITH 1 INCREMENT BY 1;

-- CRIANDO A TABELA CIDADES
CREATE TABLE CIDADES (
    ID_CIDADE integer NOT NULL PRIMARY KEY,
    NOME varchar2(31) UNIQUE NOT NULL
);

SELECT * FROM CIDADES;
-- INSERCOES EM CIDADES

--
INSERT INTO CIDADES VALUES (SEQ_CIDADES.NEXTVAL, 'Belo Horizonte');
--
INSERT INTO CIDADES VALUES (SEQ_CIDADES.NEXTVAL, 'Brasília');
--
INSERT INTO CIDADES VALUES (SEQ_CIDADES.NEXTVAL, 'Campinas');
--
INSERT INTO CIDADES VALUES (SEQ_CIDADES.NEXTVAL, 'Cancun');
--
INSERT INTO CIDADES VALUES (SEQ_CIDADES.NEXTVAL, 'Curitiba');
--
INSERT INTO CIDADES VALUES (SEQ_CIDADES.NEXTVAL, 'Florianópolis');
--
INSERT INTO CIDADES VALUES (SEQ_CIDADES.NEXTVAL, 'Frankfurt');
--
INSERT INTO CIDADES VALUES (SEQ_CIDADES.NEXTVAL, 'Honolulu');
--
INSERT INTO CIDADES VALUES (SEQ_CIDADES.NEXTVAL, 'Lisboa');
--
INSERT INTO CIDADES VALUES (SEQ_CIDADES.NEXTVAL, 'Londres');
--
INSERT INTO CIDADES VALUES (SEQ_CIDADES.NEXTVAL, 'Madrid');
--
INSERT INTO CIDADES VALUES (SEQ_CIDADES.NEXTVAL, 'Nova Iorque');
--
INSERT INTO CIDADES VALUES (SEQ_CIDADES.NEXTVAL, 'Paris');
--
INSERT INTO CIDADES VALUES (SEQ_CIDADES.NEXTVAL, 'Porto Alegre');
--
INSERT INTO CIDADES VALUES (SEQ_CIDADES.NEXTVAL, 'Recife');
--
INSERT INTO CIDADES VALUES (SEQ_CIDADES.NEXTVAL, 'Rio de Janeiro');
--
INSERT INTO CIDADES VALUES (SEQ_CIDADES.NEXTVAL, 'Roma');
--
INSERT INTO CIDADES VALUES (SEQ_CIDADES.NEXTVAL, 'Salvador');
--
INSERT INTO CIDADES VALUES (SEQ_CIDADES.NEXTVAL, 'São Paulo');
--
INSERT INTO CIDADES VALUES (SEQ_CIDADES.NEXTVAL, 'Toronto');