-- PARTE TRECHOS

-- Criando a SEQUENCIA para o ID dos TRECHOS
CREATE SEQUENCE SEQ_TRECHOS START WITH 1 INCREMENT BY 1;

-- Criando a tabela de TRECHOS
CREATE TABLE TRECHOS (
    ID_TRECHO integer PRIMARY KEY NOT NULL,
    ORIGEM varchar2(20) NOT NULL,
    DESTINO varchar2(20) NOT NULL
);

-- select