-- SEQUENCE ID AEROPORTOS
CREATE SEQUENCE SEQ_AEROPORTOS START WITH 1 INCREMENT BY 1;

-- TRIGGER ID AEROPORTOS
create or replace trigger PREENCHER_ID_AEROPORTOS before insert ON AEROPORTOS FOR EACH ROW BEGIN :NEW.ID_AEROPORTO:=SEQ_AEROPORTOS.nextval;END;

-- TABLE AEROPORTOS
CREATE TABLE AEROPORTOS (
    ID_AEROPORTO integer PRIMARY KEY NOT NULL,
    SIGLA varchar2(3) NOT NULL,
    CIDADE integer NOT NULL,
    FOREIGN KEY (CIDADE) REFERENCES CIDADES(ID_CIDADE)
);

-- SELECT AEROPORTOS IMPRIMINDO NOME DA CIDADE AO INVÉS DO ID
select ID_AEROPORTO,SIGLA,
       (select c.NOME from CIDADES c where c.ID_CIDADE = CIDADE)
        from AEROPORTOS;

-- INSERTS APÓS CRIAR O TRIGGER
INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('GRU', 19);

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('CWB', 5);

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('GIG', 16);

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('SSA', 18);

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('VCP', 3);

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('CNH', 1);

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('BSG', 2);

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('FLN', 6);

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('POA', 14);

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('REC', 15);

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('YTO', 20);

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('FCO', 17);

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('CDG', 13);

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('JFK', 12);

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('MAD', 11);

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('LHR', 10);

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('LIS', 9);

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('FRA', 7);

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('CUN', 4);

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('HNL', 8);