-- PARTE AEROPORTOS

-- Criando a SEQUENCIA para o ID dos AEROPORTOS
CREATE SEQUENCE SEQ_AEROPORTOS START WITH 1 INCREMENT BY 1;

-- Criando a tabela de AEROPORTOS
CREATE TABLE AEROPORTOS (
    ID_AEROPORTO integer PRIMARY KEY NOT NULL,
    SIGLA varchar2(3) NOT NULL,
    CIDADE varchar2(31),
    FOREIGN KEY (CIDADE) REFERENCES CIDADES(NOME)
);

-- Inserts
INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'GRU', 'São Paulo');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'CWB', 'Curitiba');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'GIG', 'Rio de Janeiro');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'SSA', 'Salvador');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'VCP', 'Campinas');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'CNH', 'Belo Horizonte');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'BSG', 'Brasília');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'FLN', 'Florianópolis');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'POA', 'Porto Alegre');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'REC', 'Recife');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'YTO', 'Toronto');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'FCO', 'Roma');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'CDG', 'Paris');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'JFK', 'Nova Iorque');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'MAD', 'Madrid');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'LHR', 'Londres');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'LIS', 'Lisboa');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'FRA', 'Frankfurt');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'CUN', 'Cancun');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'HNL', 'Honolulu');