-- SEQUENCIA ID AERONAVES
CREATE SEQUENCE SEQ_AERONAVES START WITH 1 INCREMENT BY 1;

-- TRIGGER ID AERONAVES
create or replace trigger PREENCHER_ID_AERONAVES before insert ON AERONAVES FOR EACH ROW BEGIN :NEW.ID_AERONAVE:=SEQ_AERONAVES.nextval;END;

-- Criando a tabela de AERONAVES
CREATE TABLE AERONAVES (
    ID_AERONAVE INTEGER PRIMARY KEY NOT NULL,
    FABRICANTE VARCHAR2(20) NOT NULL,
    MODELO VARCHAR2(10) NOT NULL,
    ANOFAB INTEGER NOT NULL,
    QNT_ASSENTOS INTEGER NOT NULL
);

-- Inserts após criar trigger
-- 300 Assentos = 6x50
-- 200 Assentos = 4x50
-- 124 Assentos = 4x31
INSERT INTO AERONAVES (FABRICANTE, MODELO, ANOFAB, QNT_ASSENTOS)
VALUES ('EMBRAER', 'EMBRAER195', 2013, 300);

INSERT INTO AERONAVES (FABRICANTE, MODELO, ANOFAB, QNT_ASSENTOS)
VALUES ('AirBus', 'A380', 2017, 300);

INSERT INTO AERONAVES (FABRICANTE, MODELO, ANOFAB, QNT_ASSENTOS)
VALUES ('Boeing', '787', 2001, 300);

INSERT INTO AERONAVES (FABRICANTE, MODELO, ANOFAB, QNT_ASSENTOS)
VALUES ('Boeing', '747', 2008, 200);

INSERT INTO AERONAVES (FABRICANTE, MODELO, ANOFAB, QNT_ASSENTOS)
VALUES ('EMBRAER', 'EMBRAER175', 2011, 200);

INSERT INTO AERONAVES (FABRICANTE, MODELO, ANOFAB, QNT_ASSENTOS)
VALUES ('AirBus', 'A320', 2021, 200);

INSERT INTO AERONAVES (FABRICANTE, MODELO, ANOFAB, QNT_ASSENTOS)
VALUES ('EMBRAER', 'EMBRAER190', 1999, 200);

INSERT INTO AERONAVES (FABRICANTE, MODELO, ANOFAB, QNT_ASSENTOS)
VALUES ('AirBus', 'A330', 2017, 124);

INSERT INTO AERONAVES (FABRICANTE, MODELO, ANOFAB, QNT_ASSENTOS)
VALUES ('Boeing', 'Boeing757', 2000, 124);

INSERT INTO AERONAVES (FABRICANTE, MODELO, ANOFAB, QNT_ASSENTOS)
VALUES ('Boeing', 'Boeing777', 2016, 124);