-- SEQUENCE ID AEROPORTOS
CREATE SEQUENCE SEQ_AEROPORTOS START WITH 1 INCREMENT BY 1;

-- TRIGGER ID AEROPORTOS
create or replace trigger PREENCHER_ID_AEROPORTOS before insert ON AEROPORTOS FOR EACH ROW BEGIN :NEW.ID_AEROPORTO:=SEQ_AEROPORTOS.nextval;END;

-- TABLE AEROPORTOS
CREATE TABLE AEROPORTOS (
    ID_AEROPORTO integer PRIMARY KEY NOT NULL,
    SIGLA varchar2(3) NOT NULL,
    CIDADE varchar2(31),
    FOREIGN KEY (CIDADE) REFERENCES CIDADES(NOME)
);

-- INSERTS APÓS CRIAR O TRIGGER
INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('GRU', 'São Paulo');

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('CWB', 'Curitiba');

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('GIG', 'Rio de Janeiro');

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('SSA', 'Salvador');

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('VCP', 'Campinas');

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('CNH', 'Belo Horizonte');

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('BSG', 'Brasília');

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('FLN', 'Florianópolis');

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('POA', 'Porto Alegre');

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('REC', 'Recife');

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('YTO', 'Toronto');

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('FCO', 'Roma');

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('CDG', 'Paris');

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('JFK', 'Nova Iorque');

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('MAD', 'Madrid');

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('LHR', 'Londres');

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('LIS', 'Lisboa');

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('FRA', 'Frankfurt');

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('CUN', 'Cancun');

INSERT INTO AEROPORTOS (SIGLA, CIDADE)
VALUES ('HNL', 'Honolulu');


-- INSERTS ANTES DE CRIAR O TRIGGER
INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'GRU', 'São Paulo');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'CWB', 'Curitiba');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'GIG', 'Rio de Janeiro');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'SSA', 'Salvador');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'VCP', 'Campinas');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'CNH', 'Belo Horizonte');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'BSG', 'Brasília');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'FLN', 'Florianópolis');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'POA', 'Porto Alegre');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'REC', 'Recife');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'YTO', 'Toronto');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'FCO', 'Roma');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'CDG', 'Paris');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'JFK', 'Nova Iorque');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'MAD', 'Madrid');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'LHR', 'Londres');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'LIS', 'Lisboa');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'FRA', 'Frankfurt');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'CUN', 'Cancun');

INSERT INTO AEROPORTOS (ID_AEROPORTO, SIGLA, CIDADE)
VALUES (SEQ_AEROPORTOS.NEXTVAL, 'HNL', 'Honolulu');