-- SEQUENCE ID CIDADES
CREATE SEQUENCE SEQ_CIDADES START WITH 1 INCREMENT BY 1;

-- TRIGGER CIDADES
create trigger PREENCHER_ID_CIDADE before insert on CIDADES for each row begin :NEW.ID_CIDADE := SEQ_CIDADES.nextval;END;

-- TABLE CIDADES
create table CIDADES (
    ID_CIDADE integer primary key not null,
    NOME varchar2(31) UNIQUE NOT NULL

);

-- INSERTS APÓS CRIAR O TRIGGER
INSERT INTO CIDADES(NOME) VALUES ('Belo Horizonte');
--
INSERT INTO CIDADES(NOME) VALUES ('Brasília');
--
INSERT INTO CIDADES(NOME) VALUES ('Campinas');
--
INSERT INTO CIDADES(NOME) VALUES ('Cancun');
--
INSERT INTO CIDADES(NOME) VALUES ('Curitiba');
--
INSERT INTO CIDADES(NOME) VALUES ('Florianópolis');
--
INSERT INTO CIDADES(NOME) VALUES ('Frankfurt');
--
INSERT INTO CIDADES(NOME) VALUES ('Honolulu');
--
INSERT INTO CIDADES(NOME) VALUES ('Lisboa');
--
INSERT INTO CIDADES(NOME) VALUES ('Londres');
--
INSERT INTO CIDADES(NOME) VALUES ('Madrid');
--
INSERT INTO CIDADES(NOME) VALUES ('Nova Iorque');
--
INSERT INTO CIDADES(NOME) VALUES ('Paris');
--
INSERT INTO CIDADES(NOME) VALUES ('Porto Alegre');
--
INSERT INTO CIDADES(NOME) VALUES ('Recife');
--
INSERT INTO CIDADES(NOME) VALUES ('Rio de Janeiro');
--
INSERT INTO CIDADES(NOME) VALUES ('Roma');
--
INSERT INTO CIDADES(NOME) VALUES ('Salvador');
--
INSERT INTO CIDADES(NOME) VALUES ('São Paulo');
--
INSERT INTO CIDADES(NOME) VALUES ('Toronto');