-- SEQUENCE ID CIDADES
CREATE TABLE MAPA_ASSENTOS (
    ID_MAPA INTEGER PRIMARY KEY,
    AERONAVE INTEGER NOT NULL,
    NUM_ASSENTO VARCHAR2(4) NOT NULL,
    STATUS INTEGER NOT NULL,
    BILHETE INTEGER NOT NULL,
    VOO INTEGER NOT NULL,
    FOREIGN KEY (AERONAVE) REFERENCES AERONAVES(ID_AERONAVE),
    FOREIGN KEY (NUM_ASSENTO) REFERENCES ASSENTOS(NUM_ASSENTO),
    FOREIGN KEY (STATUS) REFERENCES ASSENTOS(STATUS),
    FOREIGN KEY (VOO) REFERENCES VOOS(ID_VOO)
);

-- TRIGGER CIDADES
CREATE SEQUENCE SEQ_MAPA START WITH 1 INCREMENT BY 1;


-- TABLE CIDADES
CREATE TRIGGER PREENCHER_ID_MAPA
BEFORE INSERT ON MAPA_ASSENTOS
FOR EACH ROW BEGIN :NEW.ID_MAPA:=SEQ_MAPA.nextval;END;


-- INSERTS
