-- SEQUENCE ID CIDADES
CREATE SEQUENCE SEQ_PASSAGEM START WITH 1 INCREMENT BY 1;

-- TRIGGER CIDADES
CREATE TRIGGER PREENCHER_ID_PASSAGEM
BEFORE INSERT ON PASSAGENS
FOR EACH ROW BEGIN :NEW.ID_PASSAGEM:=SEQ_PASSAGEM.nextval;END;

-- TABLE CIDADES
create table PASSAGENS(
    ID_PASSAGEM INTEGER PRIMARY KEY,
    NOME_CLIENTE VARCHAR2(51) NOT NULL,
    EMAIL_CLIENTE VARCHAR2(51) NOT NULL,
    ID_ASSENTO INTEGER NOT NULL,
    ID_VOO INTEGER NOT NULL,
    FOREIGN KEY (ID_ASSENTO) REFERENCES ASSENTOS(ID_ASSENTO),
    FOREIGN KEY (ID_VOO) REFERENCES VOOS(ID_VOO)
);

-- INSERTS
