-- SEQUENCE ID PASSAGEM  ooooook
CREATE SEQUENCE SEQ_PASSAGEM MINVALUE 1 MAXVALUE 1000 INCREMENT BY 1;


-- TRIGGER passagem NAO SERA USADA
CREATE TRIGGER PREENCHER_ID_PASSAGEM
BEFORE INSERT ON PASSAGENS
FOR EACH ROW BEGIN :NEW.ID_PASSAGEM:=SEQ_PASSAGEM.nextval;END;

-- TABLE PASSAGEM
create table PASSAGEM(
    ID_PASSAGEM INTEGER PRIMARY KEY,
    NOME_CLIENTE VARCHAR2(51) NOT NULL,
    EMAIL_CLIENTE VARCHAR2(51) NOT NULL,
    ID_ASSENTO INTEGER NOT NULL,
    ID_VOO INTEGER NOT NULL,
    FOREIGN KEY (ID_ASSENTO) REFERENCES ASS(ID_ASSENTO),
    FOREIGN KEY (ID_VOO) REFERENCES VOOS(ID_VOO)
);

-- INSERTS
-- vou precisar passar: ID do assento (nao A10), ID do VOO
