
CREATE SEQUENCE SEQ_MAPA_DE_ASSENTOS START WITH 1 INCREMENT BY 1;

CREATE TABLE MAPA_DE_ASSENTOS (
    ID_MAPA integer PRIMARY KEY NOT NULL,
    AERONAVE integer NOT NULL,
    VOO integer NOT NULL,
    TOTAL_ASSENTOS integer NOT NULL,
    FOREIGN KEY (AERONAVE) REFERENCES AERONAVES(ID_AERONAVE),
    FOREIGN KEY (VOO) REFERENCES VOOS(ID_VOO)
);

CREATE TABLE ASSENTO (
    ID_ASSENTO integer PRIMARY KEY NOT NULL,
    NUM_ASSENTO varchar2(4) NOT NULL,
    STATUS_ASSENTO integer NOT NULL,
    COD_VOO integer NOT NULL,
    FOREIGN KEY (COD_VOO) REFERENCES VOOS(ID_VOO)
);

CREATE SEQUENCE SEQ_ASSENTO START WITH 1 INCREMENT BY 1;

SELECT * FROM MAPA_DE_ASSENTOS;
SELECT * FROM ASSENTO;




ALTER TABLE MAPA_DE_ASSENTOS
ADD CONSTRAINT unique_voo_mapa_assentos UNIQUE (VOO);






