-- SEQUENCE ID TRECHOS
CREATE SEQUENCE SEQ_TRECHOS START WITH 1 INCREMENT BY 1;

-- TRIGGER TRECHOS
create or replace trigger PREENCHER_ID_TRECHOS before insert ON TRECHOS FOR EACH ROW BEGIN :NEW.ID_TRECHO:=SEQ_TRECHOS.nextval;END;

-- TABLE TRECHOS
CREATE TABLE TRECHOS (
    ID_TRECHO integer PRIMARY KEY NOT NULL,
    CIDADE_ORIGEM integer,
    CIDADE_DESTINO integer,
    FOREIGN KEY (CIDADE_ORIGEM) REFERENCES CIDADES(ID_CIDADE),
    FOREIGN KEY (CIDADE_DESTINO) REFERENCES CIDADES(ID_CIDADE)
);

-- SELECT TRECHO IMPRIMINDO NOME DA CIDADE AO INVÉS DO ID
select ID_TRECHO, 
       (select c.NOME from CIDADES c where c.ID_CIDADE = CIDADE_ORIGEM),
        (select c.NOME from CIDADES c where c.ID_CIDADE = CIDADE_DESTINO)
        from TRECHOS;

-- INSERTS APÓS CRIAR O TRIGGER
-- São paulo para Belo Horizonte
INSERT INTO TRECHOS (CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (19, 1);

-- Trecho: De Brásilia para Campinas
INSERT INTO TRECHOS (CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (2, 3);

-- De Salvador para Porto Alegre
INSERT INTO TRECHOS (CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (18, 14);

-- Rio de Janeiro para Florianópolis
INSERT INTO TRECHOS (CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (16, 6);

-- Recife para São Paulo
INSERT INTO TRECHOS (CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (15, 19);

-- De São Paulo para Curitiba
INSERT INTO TRECHOS (CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (19, 5);

-- São Paulo para Rio de Janeiro
INSERT INTO TRECHOS (CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (19, 16);

-- São Paulo para Londres
INSERT INTO TRECHOS (CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (19, 10);

-- NY para São Paulo
INSERT INTO TRECHOS (CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (12, 19);

-- Roma para Frankfurt
INSERT INTO TRECHOS (CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (17, 7);

-- NY para Honolulu
INSERT INTO TRECHOS (CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (12, 8);

-- Lisboa para Cancun
INSERT INTO TRECHOS (CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (9, 4);

-- Madri para Paris
INSERT INTO TRECHOS (CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (11, 13);

-- Toronto para Roma
INSERT INTO TRECHOS (CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (20, 17);

-- São Paulo para Toronto
INSERT INTO TRECHOS (CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (19, 20);