-- Criar sequência
CREATE SEQUENCE SEQ_TRECHOS START WITH 1 INCREMENT BY 1;

-- Criando a tabela de TRECHOS
CREATE TABLE TRECHOS (
    ID_TRECHO integer PRIMARY KEY NOT NULL,
    CIDADE_ORIGEM integer,
    CIDADE_DESTINO integer,
    FOREIGN KEY (CIDADE_ORIGEM) REFERENCES CIDADES(ID_CIDADE),
    FOREIGN KEY (CIDADE_DESTINO) REFERENCES CIDADES(ID_CIDADE)
);

-- Select tabela
select *from CIDADES;

select ID_TRECHO, 
       (select c.NOME from CIDADES c where c.ID_CIDADE = CIDADE_ORIGEM),
        (select c.NOME from CIDADES c where c.ID_CIDADE = CIDADE_DESTINO)
        from TRECHOS;

-- Inserts
-- São paulo para Belo Horizonte
INSERT INTO TRECHOS (ID_TRECHO, CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (SEQ_TRECHOS.NEXTVAL, 19, 1);

-- Trecho: De Brásilia para Campinas
INSERT INTO TRECHOS (ID_TRECHO, CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (SEQ_TRECHOS.NEXTVAL, 2, 3);

-- De Salvador para Porto Alegre
INSERT INTO TRECHOS (ID_TRECHO, CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (SEQ_TRECHOS.NEXTVAL, 18, 14);

-- Rio de Janeiro para Florianópolis
INSERT INTO TRECHOS (ID_TRECHO, CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (SEQ_TRECHOS.NEXTVAL, 16, 6);

-- Recife para São Paulo
INSERT INTO TRECHOS (ID_TRECHO, CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (SEQ_TRECHOS.NEXTVAL, 15, 19);

-- De São Paulo para Curitiba
INSERT INTO TRECHOS (ID_TRECHO, CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (SEQ_TRECHOS.NEXTVAL, 19, 5);

-- São Paulo para Rio de Janeiro
INSERT INTO TRECHOS (ID_TRECHO, CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (SEQ_TRECHOS.NEXTVAL, 19, 16);

-- São Paulo para Londres
INSERT INTO TRECHOS (ID_TRECHO, CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (SEQ_TRECHOS.NEXTVAL, 19, 10);

-- NY para São Paulo
INSERT INTO TRECHOS (ID_TRECHO, CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (SEQ_TRECHOS.NEXTVAL, 12, 19);

-- Roma para Frankfurt
INSERT INTO TRECHOS (ID_TRECHO, CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (SEQ_TRECHOS.NEXTVAL, 17, 7);

-- NY para Honolulu
INSERT INTO TRECHOS (ID_TRECHO, CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (SEQ_TRECHOS.NEXTVAL, 12, 8);

-- Lisboa para Cancun
INSERT INTO TRECHOS (ID_TRECHO, CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (SEQ_TRECHOS.NEXTVAL, 9, 4);

-- Madri para Paris
INSERT INTO TRECHOS (ID_TRECHO, CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (SEQ_TRECHOS.NEXTVAL, 11, 13);

-- Toronto para Roma
INSERT INTO TRECHOS (ID_TRECHO, CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (SEQ_TRECHOS.NEXTVAL, 20, 17);

-- São Paulo para Toronto
INSERT INTO TRECHOS (ID_TRECHO, CIDADE_ORIGEM, CIDADE_DESTINO)
VALUES (SEQ_TRECHOS.NEXTVAL, 19, 20);